### ISSUE TITLE
Not all schemas shown in flatpak

### ISSUE THREAD

**Issue by winkelnp** [flathub/ca.desrt.dconf-editor#19] opened 2022-05-17 13:31 UTC
The issue mentioned in issue #3 still doesn't seem to be resolved for me (fedora 36)

It works fine if I add the GSETTINGS_SCHEMA_DIR variable to the flatpak (as mentioned in the previous issue)

**Comment by fedelibre** [comment] 2022-09-20 22:20
`GSETTINGS_SCHEMA_DIR=/run/host/usr/share/glib-2.0/schemas` helped! Thanks

**Comment by TingPing** [comment] 2022-09-20 23:06
This script already tries, but maybe fails, to do that: https://github.com/flathub/ca.desrt.dconf-editor/blob/master/start-dconf-editor.sh

**Comment by Arcitec** [comment] 2023-05-15 20:21
@TingPing The script works fine for me on Silverblue 38:

```sh
[johnny@fedora ~]$ flatpak run --command=bash ca.desrt.dconf-editor
[📦 ca.desrt.dconf-editor ~]$ which start-dconf-editor
/app/bin/start-dconf-editor
[📦 ca.desrt.dconf-editor ~]$ cat /app/bin/start-dconf-editor
#!/usr/bin/bash

IFS=: read -ra host_data_dirs < <(flatpak-spawn --host sh -c 'echo $XDG_DATA_DIRS')

# To avoid potentially muddying up $XDG_DATA_DIRS too much, we link the schema paths
# into a temporary directory.
bridge_dir=$XDG_RUNTIME_DIR/dconf-bridge
mkdir -p "$bridge_dir"

for dir in "${host_data_dirs[@]}"; do
  if [[ "$dir" == /usr/* ]]; then
    dir=/run/host/"$dir"
  fi

  schemas="$dir/glib-2.0/schemas"
  if [[ -d "$schemas" ]]; then
    bridged=$(mktemp -d XXXXXXXXXX -p "$bridge_dir")
    mkdir -p "$bridged"/glib-2.0
    ln -s "$schemas" "$bridged"/glib-2.0
    XDG_DATA_DIRS=$XDG_DATA_DIRS:"$bridged"
  fi
done

export XDG_DATA_DIRS
exec dconf-editor "$@"
[📦 ca.desrt.dconf-editor ~]$ /app/bin/start-dconf-editor
[📦 ca.desrt.dconf-editor ~]$ echo $XDG_DATA_DIRS
/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share
[📦 ca.desrt.dconf-editor ~]$ echo $XDG_RUNTIME_DIR
/run/user/1000
[📦 ca.desrt.dconf-editor ~]$ ls /run/user/1000/dconf-bridge/
12g2umfD8h  1fpGLTycQo	Ox6VVfsqak
[📦 ca.desrt.dconf-editor ~]$ ls -l /run/user/1000/dconf-bridge/
total 0
drwx------. 3 johnny johnny 60 May 15 22:18 12g2umfD8h
drwx------. 3 johnny johnny 60 May 15 22:16 1fpGLTycQo
drwx------. 3 johnny johnny 60 May 15 22:17 Ox6VVfsqak
[📦 ca.desrt.dconf-editor ~]$ ls -l /run/user/1000/dconf-bridge/*
/run/user/1000/dconf-bridge/12g2umfD8h:
total 0
drwxr-xr-x. 2 johnny johnny 60 May 15 22:18 glib-2.0

/run/user/1000/dconf-bridge/1fpGLTycQo:
total 0
drwxr-xr-x. 2 johnny johnny 60 May 15 22:16 glib-2.0

/run/user/1000/dconf-bridge/Ox6VVfsqak:
total 0
drwxr-xr-x. 2 johnny johnny 60 May 15 22:17 glib-2.0
[📦 ca.desrt.dconf-editor ~]$ ls -l /run/user/1000/dconf-bridge/*/*
/run/user/1000/dconf-bridge/12g2umfD8h/glib-2.0:
total 0
lrwxrwxrwx. 1 johnny johnny 38 May 15 22:18 schemas -> /run/host//usr/share//glib-2.0/schemas

/run/user/1000/dconf-bridge/1fpGLTycQo/glib-2.0:
total 0
lrwxrwxrwx. 1 johnny johnny 38 May 15 22:16 schemas -> /run/host//usr/share//glib-2.0/schemas

/run/user/1000/dconf-bridge/Ox6VVfsqak/glib-2.0:
total 0
lrwxrwxrwx. 1 johnny johnny 38 May 15 22:17 schemas -> /run/host//usr/share//glib-2.0/schemas
[📦 ca.desrt.dconf-editor ~]$ 
```

Everything looks fine? I think it's working properly. The flatpak is mapping my host's glib schema dir from what I can tell.

**Comment by Arcitec** [comment] 2023-05-15 20:30
@TingPing Yes everything is fine. My test above wasn't reading the proper, internal `$XDG_DATA_DIRS` so I changed the test as follows:

```sh
[📦 ca.desrt.dconf-editor ~]$ cat /app/bin/start-dconf-editor | sed 's,exec.*,echo "$XDG_DATA_DIRS",' | bash
/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share:/run/user/1000/dconf-bridge/NTKPdU7IZz
```

It is confirmed. Latest dconf-editor works properly and is mapping the host gschemas!

**Comment by Arcitec** [comment] 2023-05-15 23:59
@TingPing I found the issue... Kind of!

- Works: Running `flatpak run ca.desrt.dconf-editor` in a terminal.
- Doesn't work: Running dconf Editor via GNOME's launcher (the `.desktop` shortcut, in other words).

**Comment by Arcitec** [comment] 2023-05-16 00:08
@TingPing @bilelmoussaoui @A6GibKm 

I wasn't able to solve it, because the manifest already looks correct, so perhaps you know how to fix this!

The bug is very simple: The Flatpak installs a desktop file which runs:

`Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=dconf-editor ca.desrt.dconf-editor`

It should be:

`Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=start-dconf-editor ca.desrt.dconf-editor`

That will fix everything and we can finally close this 1 year old ticket.

**Comment by Arcitec** [comment] 2023-05-16 00:28
@TingPing @bilelmoussaoui @A6GibKm

All good, bug has been fixed and solution is tested. Pull request is ready:

https://github.com/flathub/ca.desrt.dconf-editor/pull/24

**Closed** 2023-05-16 17:51 UTC
