### ISSUE TITLE
It doesn't list all dconf schemas

### ISSUE THREAD

**Issue by ThanosApostolou** [flathub/ca.desrt.dconf-editor#11] opened 2019-09-29 15:09 UTC
I wanted to change some values in /org/cinnamon and as you can see in the 1st screenshot flatpak dconf-editor doesn't list it:
![Screenshot from 2019-09-29 18-04-42](https://user-images.githubusercontent.com/21288843/65834478-096bee80-e2e4-11e9-80c4-5a4f5bccd8ad.png)

After I install dconf-editor from Fedora 31 repositories then both the rpm and the flatpak package list it properly (which is weird):
![Screenshot from 2019-09-29 18-05-36](https://user-images.githubusercontent.com/21288843/65834503-40420480-e2e4-11e9-9486-ecb987da2ce8.png)

**Comment by damianatorrpm** [comment] 2019-12-29 13:07
I can confirm this for other schemas, dconf-editor not from flatpak shows them though and if navigated 
into that path from system dconf-editor, and than starting flatpak dconf-editor it says:
Nothing to show for folder "/$thepath"

**Comment by TingPing** [comment] 2019-12-29 16:09
Dconf editor needs to be completely redesigned to make any sense at all in a sandboxed world. I'll close this since its an upstream discussion.

**Closed by TingPing** 2019-12-29 16:09 UTC
