### ISSUE TITLE
dconf flatpak limited scope/functionality ?

### ISSUE THREAD

**Issue by aiamuzz** [flathub/ca.desrt.dconf-editor#4] opened 2018-10-11 08:10 UTC
Hi,

I tried to access ... the path ... `com.deepin.wrap.gnome.mutter.keybindings toggle-tiled-left` from the flatpak version of deconf ... but could not locate beyond this ...

![dconf-flatpak](https://user-images.githubusercontent.com/3283676/46790026-9a585b80-cd5b-11e8-884e-6bfd530aa5d4.png)

I installed the non-flatpak version and was able to access the path ... `com.deepin.wrap.gnome.mutter.keybindings toggle-tiled-left` ... without any problem ... as you can see here ...

![dconf-non-flatpak](https://user-images.githubusercontent.com/3283676/46789569-616bb700-cd5a-11e8-8320-433cbe80368e.png)

surprisingly after carrying out the necessary modification ... when i reopened the flatpak version of dconf editor ... i can see the the mutter folder suddenly starts showing ... which was not present in the first place.

![dconf-flatpak after](https://user-images.githubusercontent.com/3283676/46789577-692b5b80-cd5a-11e8-9783-0afd39e3d75a.png)

**Does it mean the flatpak version of dconf editor is limited in its scope / functionality compared to the non-flatpak version ... or is this some kind of bug that can be fixed ?**

**Comment by TingPing** [comment] 2018-10-11 12:40
It needs to be patched to use the host schemas. Even then though in a container world dconf-editor will now always be limited because now applications use schemas in private directories and not a single shared one.

**Comment by aiamuzz** [comment] 2018-10-11 13:10
> It needs to be patched to use the host schemas. Even then though in a container world dconf-editor will now always be limited because now applications use schemas in private directories and not a single shared one.

just like how a terminal app as a flatpak will be limited in terms of controlling the host environment ... then i guess its better to retire dconf editor as a flatpak app ... unless there are some advantages which i may not know of ?

**Comment by TingPing** [comment] 2018-10-11 13:12
No because you missed what I said. It can be patched to use host schemas that isn't hard. Even without schemas it can do some things (and maybe upstream should allow forcefully setting any key).

A terminal can be patched to run the tty one the host also.

**Comment by aiamuzz** [comment] 2018-10-11 13:20
i know i am not techy enought to understand everything :)

i didn't miss it ... i did see you said it can be patched ... also you said that application now use schema's in private directories ... so i assumed this whole patching thing would have to be repeated for all applications and each time a new one is installed ...

If this patching thing you say is a one time affair then it makes sense to continue using deconf editor in a flatpak ... but if its a continuous affair then its a disadvantage.

Can you help me out here in patching my way around this ... if its a one time affair !!!

about the terminal i saw a that a request was blocked [here](https://github.com/flathub/flathub/pull/655) ... so again i assumed that compelete host control wan't possible from a flatpak'd application ... hence the mention ... :)

**Comment by TingPing** [comment] 2018-10-11 17:55
> about the terminal i saw a that a request was blocked [here](https://github.com/flathub/flathub/pull/655)

https://github.com/flathub/flathub/pull/655#issuecomment-426662118

> also you said that application now use schema's in private directories

Well that is a different issue but a problem down the line.

**Comment by aiamuzz** [comment] 2018-10-11 17:58
about the patching ... is it a one time affair or needs to be done repeatedly ... per each application ... if so ... could you help learn the same ?

**Comment by TingPing** [comment] 2018-10-11 18:15
I left a comment on #3 which this is a duplicate of.

**Closed by TingPing** 2018-10-11 18:15 UTC

**Comment by aiamuzz** [comment] 2018-10-11 18:18
you mean if i run this command ... the patching will be done ?

`flatpak run --filesystem=host --env=GSETTINGS_SCHEMA_DIR=/run/host/usr/share/glib-2.0/schemas ca.desrt.dconf-editor`
